Resources:
  AppSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Name: leaderboard-secret
      Description: The secret for the app
      GenerateSecretString:
        SecretStringTemplate: '{"DISCORD_CLIENT_ID": "", "DISCORD_CLIENT_SECRET": ""}'
    
  AppSecretParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /leaderboard-secret/secret-arn
      Type: String
      Value: !Ref AppSecret
      Description: The ARN of the app secret
      Tags:
        project: leaderboard